[build]
builder = "NIXPACKS"

[deploy]
# Next.js will listen on $PORT in production when using `next start`
startCommand = "npm run start -- -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3


